name: ADO QA Status Update
on:
  repository_dispatch:
    types: [qa-check-ready]

jobs:
  update-qa-status:
    runs-on: ubuntu-latest
    steps:
      - name: Show received payload
        run: |
          echo "Work Item ID: ${{ github.event.client_payload.work_item_id }}"
          echo "Work Item Title: ${{ github.event.client_payload.work_item_title }}"
          echo "Work Item State: ${{ github.event.client_payload.work_item_state }}"
          
      - name: Update PR Status
        uses: actions/github-script@v7
        with:
          script: |
            console.log('GitHub Action triggered by ADO work item:', context.payload.client_payload.work_item_id);
            
            // For now, just create a simple commit status
            // You can enhance this later to find linked PRs
            console.log('QA Check passed for work item:', context.payload.client_payload.work_item_title);
